name: Run Telegram Bot

on:
  schedule:
    - cron: "*/1 * * * *"   # हर 10 मिनट पर
  workflow_dispatch:         # Manual run option

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt
- name: Save state
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add last_sent.json
        git commit -m "update state [skip ci]" || echo "No changes"
        git push

      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          GROUP_CHAT_ID: ${{ secrets.GROUP_CHAT_ID }}
          TARGET_URL: ${{ secrets.TARGET_URL }}
        run: python bot.py
